"""Manually reviewed, boundary-aware semantic bank for the 24 PFA factors.

The bank is based on the published taxonomy plus discriminative phrases and
co-occurrences audited in train.xlsx.  It is an annotation aid/model prompt
bank, not a clinical diagnostic guideline.  Every entry deliberately includes
positive language and an exclusion boundary so correlated labels are not
treated as synonyms.
"""
from configs.config import config


FIELDS = ("formal", "direct", "implicit", "train_summary", "distinction", "negative")


FACTOR_SEMANTIC_BANK = [
    dict(formal="An ongoing psychiatric disorder, clinically significant mental-health condition, diagnosis, or treatment is present.", direct="Direct cues include depression, anxiety disorder, bipolar disorder, OCD, psychosis, mentally ill, diagnosis, medication, therapist or psychiatric treatment.", implicit="Persistent symptoms seriously impair functioning over time even when no diagnosis name is stated.", train_summary="Training positives frequently mention depression, anxiety, social anxiety, OCD, severe symptoms and being mentally ill.", distinction="A temporary sad, angry or anxious reaction is emotion dysregulation or a stressful event unless an ongoing mental-health condition is supported.", negative="Do not assign solely because the author feels bad, cries once, is hopeless, or mentions another person's illness."),
    dict(formal="A physical illness, disability, injury, chronic pain, body condition or bodily characteristic affects the author.", direct="Direct cues include chronic pain, disability, disease, injury, COVID, weight, underweight, obesity, appearance or bodily limitation.", implicit="Physical symptoms, body changes or limitations interfere with daily life or contribute to distress.", train_summary="Training positives mention weight or appearance, stomach and other illness, disability, pain and medication-related bodily harm.", distinction="Financial inability to obtain care is socioeconomic status; distress caused by an event is stressful life event; self-hatred about appearance can additionally be low self-esteem.", negative="Do not assign for ordinary tiredness, metaphorical pain, or a suicide method that affects the body without a health condition."),
    dict(formal="Harmful, uncontrolled or dependent use of alcohol, recreational drugs, tobacco, or misused medication is present.", direct="Direct cues include drunk, alcohol, pot, weed, drugs, addiction, withdrawal, getting high, smoking or substance misuse.", implicit="The author relies on a substance to function or cope, loses control, or experiences harm from its use.", train_summary="Training positives prominently contain drunk, pot, alcohol and descriptions of repeated use or intoxication.", distinction="Taking prescribed medication correctly is mental-health or physical treatment; a single ordinary drink is not harmful substance use; pills as a suicide method belong to suicide means.", negative="Do not assign merely because alcohol or medication is mentioned without use, misuse, dependence, intoxication or harm."),
    dict(formal="The author believes the future cannot improve, feels trapped, sees no way out, or has lost hope.", direct="Direct cues include hopeless, no point, nothing will change, never get better, cannot go on, no future, trapped or suffering forever.", implicit="Repeated failure or pain is framed as permanent, inescapable and impossible to improve.", train_summary="Training positives often use life, no point, cannot live, anymore, suffering and no reason to continue.", distinction="Low self-esteem is a negative judgment about the self; emotion dysregulation is overwhelming feeling; meaning in life concerns purpose. Hopelessness specifically concerns future possibility.", negative="Do not assign for temporary disappointment, uncertainty or sadness when the author still expects improvement."),
    dict(formal="The author cannot adequately regulate intense sadness, anxiety, anger, panic, numbness or rapidly changing emotions.", direct="Direct cues include uncontrollable crying, panic, rage, mood swings, overwhelmed, emotional breakdown, cannot calm down or intense numbness.", implicit="Emotions dominate behaviour, escalate rapidly or feel impossible to handle even without a named disorder.", train_summary="Training positives frequently contain crying, fuck/fucking, emotions, cannot handle this, need to talk and overwhelming feelings.", distinction="Hopelessness concerns the future; low self-esteem concerns personal value; a mental disorder is persistent/clinical. Emotion dysregulation concerns control and intensity of affect.", negative="Do not assign for any ordinary mention of sadness, anger or anxiety that remains proportionate and controlled."),
    dict(formal="The author holds a persistently negative evaluation of their worth, adequacy, appearance or value to others.", direct="Direct cues include worthless, useless, ugly, pathetic, failure, burden, ashamed, hate myself, inadequate or undeserving.", implicit="The author interprets rejection or failure as proof that they are fundamentally defective or inferior.", train_summary="Training positives prominently use hate, deserve, ugly, worthless, creep, pathetic and unattractive.", distinction="Hopelessness is about the future; poor performance is an objective school outcome; perceived loneliness is poor social support. Low self-esteem is self-evaluation.", negative="Do not assign merely for regretting one action, reporting another person's insult, or feeling temporarily embarrassed without self-devaluation."),
    dict(formal="The author's academic performance is poor or has materially deteriorated.", direct="Direct cues include failing classes, failed exam, bad grades, grades dropped, cannot study, missed assignments or academic probation.", implicit="Schoolwork is repeatedly unfinished or concentration problems lead to measurable academic failure.", train_summary="Training positives strongly mention grades, grade, classes and declining or failed school performance.", distinction="School pressure without poor performance is a stressful event; inability to focus is cognitive deficit; family conflict about school is dysfunctional family.", negative="Do not assign just because the author attends school, dislikes school, fears an exam or feels academic pressure while performance remains adequate."),
    dict(formal="Poverty, unemployment, debt, homelessness or insufficient material resources significantly affects the author.", direct="Direct cues include cannot afford, no money, debt, poverty, homeless, unemployed, lost job, disability income or lacking necessities.", implicit="Housing, food, healthcare or basic stability is threatened by material insecurity.", train_summary="Training positives mention job, unemployment, disability, afford, poverty, financial hardship and lack of clothes or housing.", distinction="A job loss can also be a stressful event, but socioeconomic status requires sustained material insecurity; dissatisfaction with work alone is not poverty.", negative="Do not assign for ordinary budgeting, wanting more money, a busy job or a single purchase the author chooses not to make."),
    dict(formal="The author experiences bullying, threats, assault, sexual violence, partner violence or harmful interpersonal victimisation.", direct="Direct cues include bullied, beaten, hit, raped, assaulted, abused, threatened, attacked, controlled or made fun of.", implicit="Another person intimidates, coerces, humiliates or physically/sexually harms the author.", train_summary="Training positives include bullied, rape, treated badly, made fun of, threats and interpersonal abuse.", distinction="Violence inside the family may additionally be dysfunctional family; trauma requires an overwhelming lasting response; relationship conflict without victimisation is interpersonal difficulty.", negative="Do not assign for arguments, rejection, rude comments or self-directed harm without violence, coercion or victimisation by another person."),
    dict(formal="The post describes earlier or recurrent self-harm, suicidal ideation, planning or a suicide attempt as part of the author's history.", direct="Direct cues include attempted suicide, overdosed before, cut myself, cutting, previous attempt, used to be suicidal or tried to die.", implicit="The author refers retrospectively to surviving, relapsing, scars, repeated episodes or having nearly acted before.", train_summary="Training positives strongly contain attempted, cut, attempt, overdosed, suicide attempt, cutting and yesterday/previously.", distinction="A currently available method is suicide means; another person's suicide is exposure; present ideation without reference to prior/recurrent history is not automatically this factor.", negative="Do not assign merely from a current wish to die or current plan when no past, previous, repeated or self-harm history is expressed."),
    dict(formal="The author lacks dependable emotional or practical support and experiences loneliness, isolation, rejection, neglect or abandonment.", direct="Direct cues include no one cares, nobody understands, no one to talk to, alone, lonely, abandoned, ignored or unsupported.", implicit="People are physically present but unavailable, dismissive or unreliable when help is needed.", train_summary="Training positives frequently mention talk, need to talk, lonely, nobody cares, friends, understand and needing someone.", distinction="Interpersonal difficulty concerns forming/maintaining relationships; social support is support actually received. Poor support is the absence or failure of help.", negative="Do not assign merely because the author is physically alone temporarily, prefers solitude, or has support available and received."),
    dict(formal="The author has persistent difficulty making friends, socialising, resolving conflict or maintaining close relationships.", direct="Direct cues include no friends, cannot make friends, breakup, rejected, relationship problems, arguments, social anxiety around people or cannot connect.", implicit="Repeated interactions fail, relationships deteriorate, or the author avoids people because connection feels unmanageable.", train_summary="Training positives often mention friends, people, school, relationships, rejection and recurring social conflict.", distinction="Poor social support is lack of help; interpersonal violence requires victimisation; a single breakup may be a stressful event. This label concerns relationship functioning.", negative="Do not assign for one ordinary disagreement, chosen solitude, or simply having few people when the author reports adequate relationships."),
    dict(formal="The family or home environment is unstable, neglectful, abusive, rejecting or persistently conflictual.", direct="Direct cues include abusive parents, toxic family, parents fight, neglect, kicked out, controlling mother/father, divorce, family hates me or unsafe home.", implicit="Caregivers repeatedly invalidate needs, impose harmful control or fail to provide safety and care.", train_summary="Training positives prominently mention parents, family, dad, mom, father, brother, refusal, hatred and home conflict.", distinction="Violence by a family member may also be interpersonal violence; ordinary relationship difficulty outside the family is interpersonal difficulty; one family event is not necessarily dysfunction.", negative="Do not assign for a normal isolated disagreement, a supportive family member, or merely mentioning family without harmful functioning."),
    dict(formal="The author is affected by another person's suicidal thoughts, attempt or death by suicide.", direct="Direct cues include my friend attempted, my brother killed himself, someone died by suicide, found them, witnessed an attempt or suicide loss.", implicit="The author describes grief, fear, imitation or emotional impact after learning of another person's suicidality.", train_summary="Rare training positives refer to a brother, friend or other person, suicide deaths/attempts, crying, numbness and grief.", distinction="The author's own prior suicidality is prior self-harm; losing someone for a non-suicide reason is stressful/traumatic loss; responsibility for keeping someone alive is a separate protective factor.", negative="Do not assign when the only suicidal person is the author, or when another person's death is not described as suicide."),
    dict(formal="A concrete recent or ongoing life event creates significant stress, including breakup, bereavement, job, school, legal, financial, health or relocation problems.", direct="Direct cues include breakup, lost job, exam, eviction, death, COVID, quarantine, divorce, deadline, move or recent crisis.", implicit="Distress begins or worsens after an identifiable change, loss, failure or external pressure.", train_summary="Training positives often mention COVID/corona, quarantine, months ago, job problems, breakup, loss and recent changes.", distinction="Traumatic experience exceeds coping and often has lasting trauma symptoms; chronic poverty is socioeconomic status; general emotion without an event is emotion dysregulation.", negative="Do not assign solely from longstanding mood symptoms when no identifiable event or change is present."),
    dict(formal="An overwhelming event such as severe abuse, assault, violence, disaster or profound loss exceeds coping ability and continues to affect the author.", direct="Direct cues include traumatized, PTSD, rape, severe abuse, flashbacks, nightmares, cannot forget, witnessed violence or lasting trauma.", implicit="The author remains psychologically altered, fearful, numb or intrusive memories persist after a disturbing experience.", train_summary="Training positives frequently mention abused, abuse, rape, bullied, abusers and continuing effects of severe experiences.", distinction="Interpersonal violence identifies victimisation itself; stressful life event need not be overwhelming or lasting. Trauma requires severity or a sustained traumatic response.", negative="Do not assign every breakup, exam, argument or unpleasant memory as trauma without overwhelming severity or continuing traumatic impact."),
    dict(formal="Attention, memory, concentration, decision making, reasoning or clear thinking is impaired.", direct="Direct cues include cannot focus, cannot concentrate, brain fog, forget everything, confused, cannot decide, memory problems or thoughts stuck.", implicit="The author cannot organise tasks, solve problems or sustain thought even when trying.", train_summary="Training positives strongly mention focus, concentrate, unable to think, memory, sleep-related cognitive impairment and being stuck.", distinction="Poor school performance is an outcome; rumination from intense emotion alone is emotion dysregulation; a clinical disorder requires broader persistent symptoms.", negative="Do not assign ordinary indecision, changing one's mind, lack of motivation or one distraction without impaired cognition."),
    dict(formal="A suicide method, instrument, location or lethal substance is considered and the author has or plausibly can obtain access to it.", direct="Direct cues include gun, pills, rope, bridge, jump, overdose, poison, knife, train, height, hang or a prepared method.", implicit="The author describes acquiring, storing, approaching, preparing or being near a lethal method or location.", train_summary="Training positives prominently mention bridge, jump, gun, overdose/OD, hang, pills and jump from bridge.", distinction="Past use of a method belongs to prior attempt; a vague wish to die without method is ideation/hopelessness; ordinary medication possession is not suicide means without suicidal use/access context.", negative="Do not assign figurative phrases, hypothetical methods discussed generally, or inaccessible methods with no indication the author could use them."),
    dict(formal="Distress is specifically related to sexual orientation, gender identity, coming out, same-sex relationships, stigma, discrimination or identity-based rejection.", direct="Direct cues include gay, lesbian, bisexual, trans, queer, questioning, coming out, homophobic, gender identity or rejected for orientation.", implicit="The author fears disclosure, conceals identity, experiences identity conflict or loses relationships because of LGBTQ+ stigma.", train_summary="Very rare training positives mention sexual identity, partner conflict, rejection, discrimination and identity-related hopelessness.", distinction="Bullying or family conflict only qualifies here when explicitly linked to sexual orientation or gender identity; general romantic rejection is interpersonal difficulty.", negative="Do not infer sexual orientation from gendered partners, sexual activity, assault, or the word partner without identity-related distress."),
    dict(formal="The author actually receives emotional, practical, professional or community support from another person.", direct="Direct cues include my friend listened, family helped, partner stayed, therapist supports me, doctor helped, people care or someone checked on me.", implicit="Another person provides presence, safety, advice, resources or reliable understanding that benefits the author.", train_summary="Training positives mention listened, help received, caring friends/family, professional support and people actively solving problems together.", distinction="Seeking help is coping strategy; merely having people nearby is not support; poor social support is absence or failure of help. This label requires support received or clearly available.", negative="Do not assign when the author asks strangers for help but has not received it, says nobody cares, or only hopes someone will support them."),
    dict(formal="The author actively uses a strategy or behaviour to manage distress, solve problems, obtain help or remain safe.", direct="Direct cues include therapy, called a hotline, talked to someone, exercise, music, hobbies, journaling, distraction, medication, breathing, planning or asking for advice.", implicit="The author takes constructive or deliberate action to regulate feelings, reduce danger or change the situation, even if it is only partly effective.", train_summary="Training positives frequently contain talk, need help, therapist, therapy, tried, asking advice and concrete attempts to cope.", distinction="Social support is help received; psychological capital is inner hope/confidence; merely using alcohol/drugs may be substance use rather than adaptive coping.", negative="Do not assign passive wishing, suicidal action, uncontrolled avoidance, or saying 'I need help' without any help-seeking or coping action."),
    dict(formal="The author expresses hope, optimism, resilience, confidence, self-efficacy, perseverance or belief that recovery is possible.", direct="Direct cues include I can get better, still have hope, proud, strong enough, things will improve, I will keep trying or recovery is possible.", implicit="Despite distress, the author retains agency, positive expectation, gratitude or confidence in surviving and improving.", train_summary="Training positives often mention hope, happy, love, thankfulness, wanting a better life, not wanting to die and believing improvement is possible.", distinction="Meaning in life supplies purpose; responsibility supplies duty; coping is an action. Psychological capital is a positive internal belief or resource.", negative="Do not assign from a polite thank-you, momentary happiness, love mentioned only as a loss, or a goal expressed with no hope or confidence."),
    dict(formal="A duty, promise, caregiving role or obligation toward self, family, children, friends, pets, work or others influences the author's survival or actions.", direct="Direct cues include my children need me, cannot hurt my family, must care for my pet, promised someone, people depend on me or I have responsibilities.", implicit="Concern about burdening or harming loved ones restrains suicide, or a role makes the author feel obliged to continue.", train_summary="Training positives often mention hurting people, friends who care, feeling bad for others, duties and someone or something depending on the author.", distinction="Meaning in life is purpose/value; social support is help received; low self-esteem may include feeling like a burden. Responsibility requires an obligation that guides behaviour.", negative="Do not assign merely because family or pets are mentioned, because the author feels burdensome, or because others care without an expressed duty or obligation."),
    dict(formal="The author identifies purpose, values, goals, dreams, commitments or reasons for living that give life direction and significance.", direct="Direct cues include reason to live, purpose, life goal, dream, future plan, something to live for, values, meaningful work or want to graduate.", implicit="A valued relationship, activity or future possibility makes continuing life matter beyond immediate survival.", train_summary="Training positives mention wanting a life, graduating, future goals, reasons not to die, meaningful relationships and plans that motivate continuation.", distinction="Responsibility is duty to others; psychological capital is confidence/hope; coping is an action. Meaning in life is enduring significance or direction.", negative="Do not assign every short-term task, vague wish to feel better, enjoyable distraction or obligation unless it is described as meaningful purpose or a reason to live."),
]


def _classifier_prompts(entry):
    return [
        entry["formal"], entry["direct"], entry["implicit"], entry["train_summary"],
        ("Assign this factor when: " + entry["formal"] + " " + entry["direct"]
         + " Boundary: " + entry["distinction"] + " Exclude: " + entry["negative"]),
    ]


FACTOR_CLASSIFIER_PROMPTS = [_classifier_prompts(entry) for entry in FACTOR_SEMANTIC_BANK]

if len(FACTOR_SEMANTIC_BANK) != config.NUM_FACTORS:
    raise ValueError("Semantic bank must contain exactly one entry per factor")
for label, entry in zip(config.FACTOR_LABELS, FACTOR_SEMANTIC_BANK):
    missing = set(FIELDS) - set(entry)
    if missing or any(not str(entry[field]).strip() for field in FIELDS):
        raise ValueError(f"Incomplete semantic entry for {label}: {sorted(missing)}")
if any(len(prompts) != 5 for prompts in FACTOR_CLASSIFIER_PROMPTS):
    raise ValueError("Every factor must expose five classifier prompts")
